language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    pckages:
node_js:
  - stable
  - '6'
install:
  - npm install -g polymer-cli
  - polymer install
before_script:
  - polymer lint
script:
  - xvfb-run npm test
