language: node_js
sudo: false
dist: trusty
node_js:
  - "stable"
  - "6"
addons:
  firefox: "latest"
  chrome: "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
